### PR TITLE
Import news

### PR DESCRIPTION
**Pull request by akmiller01**
Beginning of script to import news. Once we have a branch with both news and events we can expand.

### CODE REVIEW

**Comment by akmiller01** [comment]
Import working flawlessly now. Only major concern is that all links/image sources still reference aidtransparency.net... Here's the exporter:

```
import json
import pandas as pd
import requests
from bs4 import BeautifulSoup
import dateutil.parser as dparser

news_articles = []

for i in range(1, 41):
    print(i)
    url = "https://www.aidtransparency.net/category/news/page/"+str(i)
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "lxml")
    links = soup.select("a.post-title-link")
    imgs = soup.select(".article-image a img")
    for j in range(0, len(links)):
        link = links[j].get('href')
        title = links[j].text
        img = imgs[j].get('src')
        article_soup = BeautifulSoup(requests.get(link).content, "lxml")
        date = dparser.parse(article_soup.select("p.meta")[0].text.split("\n")[1], fuzzy=True).strftime("%Y-%m-%d")
        article_children = article_soup.find("article").find_all(recursive=False)
        content = ""
        for child in article_children:
            if child.get('class'):
                if child.get('class')[0] not in ["post-title", "meta"]:
                    content += str(child)
            else:
                content += str(child)
        article_dict = {"link": link, "img": img, "title": title, "date": date, "content": content}
        news_articles.append(article_dict)

pd.DataFrame(news_articles).to_csv("news.csv")
with open('news.json', 'w') as outfile:
    json.dump(news_articles, outfile)
```

**Comment by akmiller01** [comment]
New exporter with tokenization for guessing at news/events dichotomy:

```
import json
import pandas as pd
import requests
from bs4 import BeautifulSoup
import dateutil.parser as dparser
from nltk.tokenize import RegexpTokenizer

news_articles = []
event_key_words = ["meet", "register", "workshop", "join", "meeting", "attend"]
tokenizer = RegexpTokenizer(r'\w+')

for i in range(1, 41):
    print(i)
    url = "https://www.aidtransparency.net/category/news/page/"+str(i)
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "lxml")
    links = soup.select("a.post-title-link")
    imgs = soup.select(".article-image a img")
    for j in range(0, len(links)):
        link = links[j].get('href')
        title = links[j].text
        title_tokens = [w.lower() for w in tokenizer.tokenize(title) if w.isalpha()]
        common_tokens = list(set(event_key_words).intersection(title_tokens))
        article_type = "event" if len(common_tokens) > 0 else "news"
        img = imgs[j].get('src')
        article_soup = BeautifulSoup(requests.get(link).content, "lxml")
        date = dparser.parse(article_soup.select("p.meta")[0].text.split("\n")[1], fuzzy=True).strftime("%Y-%m-%d")
        article_children = article_soup.find("article").find_all(recursive=False)
        content = ""
        for child in article_children:
            if child.get('class'):
                if child.get('class')[0] not in ["post-title", "meta"]:
                    content += str(child)
            else:
                content += str(child)
        article_dict = {"link": link, "img": img, "title": title, "date": date, "content": content, "type": article_type}
        news_articles.append(article_dict)

pd.DataFrame(news_articles).drop(['content'], 1).to_csv("news.csv")
with open('news.json', 'w') as outfile:
    json.dump(news_articles, outfile)
```

**Comment by akmiller01** [comment]
https://github.com/IATI/preview-website/pull/128 and https://github.com/IATI/preview-website/pull/11 need merging first.

**Comment by allthatilk** [comment]
LGTM and not worried about tests as this is a temporary addition for import so when #128 and #11 are merged this one is good to go!

**Pull request merged**
