### PR TITLE
Rename IATIStreamBlock fields

### PR DESCRIPTION
**Pull request by andylolz**
h2, h3 and h4 don’t meet pylint spec for variable names.

This affects the button text in the admin interface, but I think it makes it a bit clearer:

screen shot 2018-07-13 at 19 09 30

### CODE REVIEW

**Comment by andylolz** [comment]
The alternative to this is just to add `# pylint: disable=invalid-name` to the following lines:

https://github.com/IATI/preview-website/blob/38d0107927e94cc435101dae320dcdf09988ba21/iati/home/models.py#L76-L78

…which would also be fine, imo.

**Comment by allthatilk** [comment]
@andylolz subtractions and changes to streamfields pose one of the more substantial risks of breaking migrations in this project so it doesn't seem worth risking for the sake of linting. Our preference is for the lines to disable the linters for these variables.

**Comment by andylolz** [comment]
Cool – closing in favour of #208.

**Comment by andylolz** [comment]
Turns out this PR was totally wrong anyway, since migrating a streamblock also requires a data migration.

**Pull request closed without merging**
