### PR TITLE
Reorder children

### PR DESCRIPTION
**Pull request by akmiller01**
Unfortunately branched this feature from refactor-people instead of add-about-models, so apologies about that in advance. This has also subsumed https://github.com/IATI/preview-website/pull/68 so closing that one.

The logic here is to create an orderable on every parent page that contains the child pages. Instances of the orderable are created on save of the children. I tried to disable the user from changing the orderable dropdown on the parent page, but disabling it also disabled the ability to reorder.

### CODE REVIEW

**Comment by dalepotter** [comment]
Was just reviewing this one and it got me thinking about if there were alternative approaches to a new model that appears to the user in the 'Multilingual' tab. In particular, the issue about what happens when a user deletes a page from the child menu list made me wonder about if this adds a layer of confusion content managers. 

I was googling around and found this default functionality of the [wagtail content editor](http://docs.wagtail.io/en/v2.0.1/editor_manual/finding_your_way_around/the_explorer_page.html#reordering-pages) which might already do exactly what we are looking for. I tried it on the `refactor-people` branch and it seems to work, though not particularly intuitive to content editors, since the default order of pages in the editor seems to be by title, then only by clicking the  icon do you get the actual order.

**Comment by akmiller01** [comment]
When you reorder the child pages, are they permanently stuck in that order?
Or does it reshuffle pages to the top when you edit them?

**Comment by dalepotter** [comment]
> When you reorder the child pages, are they permanently stuck in that order?
Or does it reshuffle pages to the top when you edit them?

This is the bit which I imagine would seem confusing to content editors.  When you edit a page the actual page order is unchanged (accessed via the method I mentioned), however the order the default in the editor panel order is by last updated.

**Default content editor view (i.e. sorted by last update)**
image

**Page ordering functionality enabled (i.e. order unchanged(**
image

The order in the sub-menu corresponds with the page ordering view
image

**Comment by akmiller01** [comment]
Cool, much easier solution. Imogen and I had found that in the docs last
week, but we couldn't figure out which button they were talking about so I
assumed it was a feature that had recently been taken out!

**Comment by akmiller01** [comment]
Closing due to built-in solution

**Pull request closed without merging**
