### PR TITLE
[Needs tests] Get search styled up and working

### PR DESCRIPTION
**Pull request by andylolz**
It looks like this:
screen recording 2018-08-22 at 03 56 pm

It’s based on the following related templates:

 * http://styles.iatistandard.org/page-templates/02-6-knowledgebase-search-results
 * http://styles.iatistandard.org/page-templates/02-6a-knowledgebase-search-zero-results

### CODE REVIEW

**Comment by andylolz** [comment]
TODO:

 - [x] templatise
 - [ ] add a functional test or two
 - [ ] add an index so that search is on content as well as titles?

**Comment by andylolz** [comment]
I’ve deviated from the design a bit, to use the `placeholder` attribute for the placeholder text on the input.

I think the pagination needs some work, too (e.g. highlight current page; only show some maximum number of pages) but I’ve just stuck to the designs there.

**Comment by akmiller01** [comment]
Hi @andylolz. Search is looking good.

For pagination I think what we've put at the bottom of the news_index_page would work well. 
image If `search_results` is Django paginator object you should be able to use the include like so:
```
{% include 'home/includes/pagination_links.html' with children=search_results %}
```

We've also started the process of internationalization. If you have any static strings in your templates could you please `{% load i18n %}` at the top and then include the strings in either a `{% trans "English string" %}` or `{% blocktrans %}Long english string with {{ vars }}{% endblocktrans %}` Again we've got some good examples on news_index_page https://github.com/IATI/preview-website/blob/master/iati/news/templates/news/news_index_page.html#L17 Once this feature is merged we can regenerate the .po translation files here: https://github.com/IATI/preview-website/pull/253

Let me know if you need some guidance getting started on tests. I'm quite curious to see how the default wagtail search function deals with our `wagtail_modeltranslation` dependency! It would be nice if searching on `heading` dynamically pulls on `heading_en` or `heading_fr` depending on the user context...

**Comment by andylolz** [comment]
Hi @akmiller01! Thanks for taking a look at this.

> For pagination I think what we've put at the bottom of the news_index_page would work well.

^^ Looks good! I’ll do that.

Yep, I saw you’re working on translation. No problem – I’ll update accordingly, and will leave it with you to update po files.

> It would be nice if searching on `heading` dynamically pulls on `heading_en` or `heading_fr` depending on the user context...

^^ I checked this at the time, but I’m afraid I’ve forgotten the result. I thiiiiink the answer may have been “yes” but I wouldn’t swear on it and I regret not making a note!

**Comment by andylolz** [comment]
@akmiller01: Ah, I won’t be continuing on this after all.

Feel free to push to this branch, or alternatively close and continue elsewhere.

I’ll leave it open in case that’s helpful.

**Comment by samuele-mattiuzzo** [comment]
Thanks for this Andy!
Holding this currently, we will look at this when we have our next website sprint (dates tbc), but will most likely bug you when the time comes!

**Comment by samuele-mattiuzzo** [comment]
quick-update on this: coming next Tuesday (25th), we will have a 2-weeks sprint where this work will be resumed and completed

**Comment by samuele-mattiuzzo** [comment]
Parked it again (briefly) while waiting for Fffunction's updates then will finish and merge

**Comment by andylolz** [comment]
Woo! Thanks! 🚀

**Pull request merged**
