### PR TITLE
Run django/wagtail functional tests on Travis

### PR DESCRIPTION
**Pull request by dalepotter**
Configures TravisCI to fully build Django/Wagtail and run functional tests using Firefox in headless mode.

Note for review: Commits 5ca85bd and before already exist in `dev`.

After this is merged to `add-page-models`, all PRs based from `add-page-models` will automatically run functional tests (hopefully with a nice green tick when everything passes 👍) Note as per PR #108 Travis also runs code linting checks, but only when merging to the `dev` and `master` branches.

To dos:
- [x] Resolve merge conflicts between this branch (based from `dev`) and `add-page-models`
- [x] Configure and setup postgres database on Travis
- [x] Fully build django/wagtail on Travis
- [x] Setup Firefox in headless mode on Travis
- [x] Show builds pass

### CODE REVIEW

**Comment by allthatilk** [comment]
I'm getting this error trying to run this locally:

```
(preview-site) ➜  iati git:(run-functional-tests-with-travis) pytest
Traceback (most recent call last):
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/_pytest/config.py", line 329, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/imogenk/IATI/preview-website/iati/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/_pytest/config.py", line 360, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/imogenk/IATI/preview-website/iati/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/Users/imogenk/IATI/preview-website/iati/tests/conftest.py", line 6, in <module>
    from django.contrib.auth.models import User
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/imogenk/.virtualenvs/preview-site/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
ERROR: could not load /Users/imogenk/IATI/preview-website/iati/tests/conftest.py
```

**Comment by dalepotter** [comment]
> I'm getting this error trying to run this locally:
@allthatilk this is a very strange error that I have spent a couple hours trying to debug. I would expect Travis to get that same error, but it runs fine. Also the only reliable way that switching branches seems to resolve the bug:
```
git checkout dev
git checkout run-functional-tests-with-travis
```

From there, the only way that I've found to reproduce the problem is to clone this branch of the project from scratch - i.e. `git clone --branch=run-functional-tests-with-travis https://github.com/IATI/preview-website.git IATI/preview-website`. It's very strange and as such I'm inclined to say this is a local dev problem, and not with the code.

**Comment by akmiller01** [comment]
Hey @dalepotter Unfortunately your suggested fix didn't work for me. Same error as Imogen until I move conftest.py from tests up a folder to iati.

**Comment by allthatilk** [comment]
This one seems to work for me now I've rebuilt my virtualenv. @akmiller01 have you got the tests working for you now too?

**Pull request merged**
