### PR TITLE
[Blocked][Needs tests] Sort upcoming events chronologically by start date

### LINKED ISSUE #193: Upcoming events aren’t sorted chronologically
TAG is in November; the MA is in July. So I’d expect to see the MA listed before the TAG on the events page. And yet:

screen shot 2018-07-09 at 00 10 21

The later event is shown before the earlier one because currently, upcoming events are sorted **reverse chronologically** by start date:
https://github.com/IATI/preview-website/blob/fdf0238eea1c49e453876189dafed7aa59374c4c/iati/events/models.py#L33

While that makes sense for past events (because for past events, it’s common to start from ‘now’ and work backwards), it’s a bit jarring for upcoming events (where it’s common to start from ‘now’ and work forwards).

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #193.

~~Again, I should stipulate that I haven’t tested this locally.~~ Tested locally; works for me.

### CODE REVIEW

**Comment by allthatilk** [comment]
@andylolz Nice work, we're being a lot stricter on tests with this new shiny so we won't be able to approve this PR until we have at least unit tests for the event ordering. Our current tests are in need of a clean up due to time pressures which is our priority at the moment. We'll let you know once we're in a better place to advice on what testing would be ideal for this.

**Comment by allthatilk** [comment]
Refactoring of tests has now been deprioritised for other work. I am unlikely to get to finish this work myself. I have opened issue #224 to highlight the need to look into the refactoring of these tests again in the future.

**Comment by allthatilk** [comment]
@andylolz I'm afraid we ran out of time for the test refactoring work and it has now been deprioritised. Unit tests at a minimum using pytest should be sufficient. The tests should sit in an `events_unit_tests.py` file in the tests dir. I defer all other choices to you.

**Comment by andylolz** [comment]
> The tests should sit in an `events_unit_tests.py` file in the tests dir. I defer all other choices to you.

Kk then I think this PR probably relies on another PR that adds event unit tests. I doubt I’m going to do do that one, so I’m going to close this one.

**Comment by akmiller01** [comment]
@samuele-mattiuzzo still working after last merge dev: 
image

Just looked over the code, this isn't really possible to feature test; just making changes to the internal functions of the event_index_page.

**Comment by andylolz** [comment]
> Just looked over the code, this isn't really possible to feature test; just making changes to the internal functions of the event_index_page.

I’m pleased this got merged, but I don’t agree with the premise that it’s not possible to add feature tests here. This changes site functionality – you can definitely feature test it. Add two events with different dates. Before the PR, they’ll be sorted one way, after the PR they’ll be sorted the opposite way. Or alternatively do it with unit tests.

**Pull request merged**
